### ISSUE TITLE
Camera not work as expected on android 

### ISSUE THREAD

**Issue by BEGDAR8ZOUHAIR** [mrevanzak/hue-lens#1]
i fixed the app/build.gradle and build.gradle  change to 
 minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '26')
 but camera not work good and  screshot not work

**Comment by mrevanzak** [comment]
thanks for pointing it out. havent test it on android yet because i dont have the device. will fix it later

**Comment by mrevanzak** [comment]
can you try again @BEGDAR8ZOUHAIR
